---
# I have some personal opinions that disagree with the Ruby Style Guide. These checks have been intentionally disabled to support
# my preferred coding style.
AllCops:
  TargetRubyVersion: 2.5.1
Layout/CaseIndentation:
  Enabled: false
Layout/IndentArray:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/RescueException:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
#Style/ConditionalAssignment:
#  Enabled: false
# Metrics/AbcSize:
#   Enabled: false
# Metrics/ClassLength:
#   Enabled: false
# Style/SymbolArray:
#   Enabled: false
# Layout/ExtraSpacing:
#   Enabled: false
# Layout/SpaceBeforeFirstArg:
#   Enabled: false
#Style/GuardClause:
#  Enabled: false
#Metrics/MethodLength:
#  Max: 20
