---
# I have some personal opinions that disagree with the Ruby Style Guide. These checks have been intentionally disabled to support
# my preferred coding style.
AllCops:
  TargetRubyVersion: 2.5.1
Layout/AlignHash:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/IndentArray:
  Enabled: false
Layout/IndentHash:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
