AllCops:
  TargetRubyVersion: 2.5.1
Metrics/LineLength:
  Enabled: false
#Style/GuardClause:
#  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/NegatedIf:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Lint/RescueException:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
